version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: neo_event_db
    restart: always
    environment:
      POSTGRES_USER: neo_user
      POSTGRES_PASSWORD: neo_password
      POSTGRES_DB: neo_event_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
